import React from "react";

function Stars() {
  return (
    <div>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
        <star></star>
    </div>
  );
}

export default Stars;
